//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Diagnostics.CodeAnalysis;
using System.Resources;

[assembly: AssemblyTitle("Insight.Database Schema")]
[assembly: AssemblyCompany("Insight")]
[assembly: AssemblyProduct("Insight")]
[assembly: AssemblyCopyright("Copyright © Jon Wagner, used by permission")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

[assembly: NeutralResourcesLanguageAttribute("en-US")]

[assembly: InternalsVisibleTo("Insight.Database.Schema.Tests")]
